import type { Metadata } from "next";
// Imports the Metadata type for setting up page titles and descriptions (used for SEO).

import { StackProvider, StackTheme } from "@stackframe/stack";
// Imports components from Stack (used for authentication and theming).
// StackProvider gives access to authentication and session info across your app.
// StackTheme ensures consistent theming for Stack UI elements.

import { stackServerApp } from "@/stack/server";
// Imports your configured Stack app (server-side setup with API keys, etc.)

import { Geist, Geist_Mono } from "next/font/google";
// Imports two Google fonts using Next.js font optimization (Geist Sans & Geist Mono).

import "./globals.css";
// Imports global CSS for consistent styling across the entire app.

import { Navbar } from "./navbar";
import { Footer } from "./footer";
// Imports your site's navigation bar and footer components.

// Load custom fonts and assign them to CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata (appears in browser tab and search results)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The root layout wraps every page in your app — it defines global structure and providers.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // The page content that will be injected inside this layout
}>) {
  return (
    <html lang="en">
      {/* Sets the language attribute for accessibility and SEO */}

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Applies both custom fonts and enables smoother text rendering (antialiased)
      >
        {/* 
          The StackProvider wraps the entire app, giving all pages access 
          to authentication, user sessions, and Stack's context.
        */}
        <StackProvider app={stackServerApp}>
          {/* StackTheme applies Stack's design system and theme styling */}
          <StackTheme>
            {/* The Navbar stays at the top of every page */}
            <Navbar />

            {/* This renders whatever page is currently active */}
            {children}

            {/* The Footer stays at the bottom of every page */}
            <Footer />
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
